name: buid images

on:
  push:
    tags:
    - 'v[0-9].[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          GIT_COMMIT=$(git rev-parse --short "$GITHUB_SHA")
          IMAGE=${{ secrets.REGISTRY }}/llaoj/kube-eventer-amd64:$VERSION-$(GIT_COMMIT)-llaoj
          docker build -f deploy/Dockerfile -t $IMAGE .
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY }}
          docker push $IMAGE